---
#base image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - init: dep ensure
  - init: go get -v -t -d ./...
  - init: go get -d github.com/sylabs/singularity
  - init: export VERSION=v3.0.3 && \
    cd $GOPATH/src/github.com/sylabs/singularity && \
    git fetch && \
    git checkout $VERSION